[package]
name = "three-d-io"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2021"
description = "Load/save functionality for 3d applications."
license = "MIT"
readme = "README.md"
repository = "https://github.com/asny/three-d-io"
categories = ["graphics", "rendering", "visualization", "webassembly"]
keywords = ["3d", "gamedev", "graphics", "wasm"]
exclude = [".gitignore"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["img", "mesh", "vol"]
https = ["reqwest"]
# Image formats
img = ["jpeg", "png"]
jpeg = ["image/jpeg"]
png = ["image/png"]
# Mesh formats
mesh = ["obj", "gltf"]
obj = ["wavefront_obj"]
# Volume formats
vol = []

[dependencies]
cgmath = "0.18"
three-d-data-types = { path = "../three-d-data-types" }
thiserror = "1.0"
reqwest = {version = "0.11", optional = true }
gltf = { version = "1.0", features = ["utils"], optional = true }
wavefront_obj = { version = "10.0", optional = true }
image = { version = "0.23", optional = true, default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "farbfeld"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = "0.4"